import Vue from 'vue'
import {
	ViewBox, XHeader, Tabbar, TabbarItem, Group, Cell, XInput, Swiper, SwiperItem,
	XProgress, Scroller, Tab, TabItem, Search, XButton, AlertPlugin,CheckIcon,
	Selector, Actionsheet, Popup,PopupHeader, Radio, Datetime, XAddress, XTextarea,Checklist, PopupPicker,
	XSwitch, ToastPlugin, LoadingPlugin,ConfirmPlugin,Flexbox,FlexboxItem,Confirm,Swipeout, SwipeoutItem, SwipeoutButton
	} from 'vux'
Vue.component('view-box', ViewBox)
Vue.component('x-header', XHeader)
Vue.component('tabbar', Tabbar)
Vue.component('tabbar-item', TabbarItem)
Vue.component('group', Group)
Vue.component('cell', Cell)
Vue.component('x-input', XInput)
Vue.component('swiper', Swiper)
Vue.component('swiper-item', SwiperItem)
Vue.component('x-progress', XProgress)
Vue.component('scroller', Scroller)
Vue.component('tab', Tab)
Vue.component('tab-item', TabItem)
Vue.component('search', Search)
Vue.component('x-button', XButton)
Vue.component('selector', Selector)
Vue.component('actionsheet', Actionsheet)
Vue.component('popup', Popup)
Vue.component('popup-picker', PopupPicker)
Vue.component('popup-header',PopupHeader)
Vue.component('radio', Radio)
Vue.component('check-list', Checklist)
Vue.component('datetime', Datetime)
Vue.component('x-address', XAddress)
Vue.component('x-textarea', XTextarea)
Vue.component('x-switch', XSwitch)
Vue.component('flexbox',Flexbox)
Vue.component('flexbox-item',FlexboxItem)
Vue.component('confirm', Confirm)
Vue.component('swipeout',Swipeout)
Vue.component('swipeout-item',SwipeoutItem)
Vue.component('swipeout-button',SwipeoutButton)
Vue.component('check-icon', CheckIcon)
Vue.use(AlertPlugin)
Vue.use(ToastPlugin)
Vue.use(LoadingPlugin)
Vue.use(ConfirmPlugin)

